spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Demonstrates outbound HTTP calls"
name = "outbound-http"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "outbound-http"

[component.outbound-http]
source = "outbound-http/target/wasm32-wasi/release/http_rust_outbound_http.wasm"
allowed_outbound_hosts = ["https://random-data-api.fermyon.app"]
[component.outbound-http.build]
workdir = "outbound-http"
command = "cargo build --target wasm32-wasi --release"
